apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartbp.fullname" . }}
  labels:
    {{- include "chartbp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.portGrpc }}
      targetPort: {{ .Values.service.portGrpc }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "chartbp.selectorLabels" . | nindent 4 }}
