apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appLabels.app }}
  labels:
    {{- include "chartbp2.labels" . | nindent 4 }}
    app: {{ .Values.appLabels.app }}
    project: {{ .Values.appLabels.project }}
    env: {{ .Values.appLabels.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
  {{ end }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.grpcService.enabled }}
    - port: {{ .Values.grpcService.port }}
    {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.grpcService.nodePort}}
  {{ end }}
      targetPort: {{ .Values.grpcService.port }}
      protocol: TCP
      name: {{ .Values.grpcService.type }}
  {{- end }}
  selector:
    {{- include "chartbp2.selectorLabels" . | nindent 4 }}
