{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chartbp2.serviceAccountName" . }}
  labels:
    {{- include "chartbp2.labels" . | nindent 4 }}
    app: {{ .Values.appLabels.app }}
    project: {{ .Values.appLabels.project }}
    env: {{ .Values.appLabels.env }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
